-- Ejecutar una sola vez en Supabase (Dashboard → SQL Editor → New query → Run).
-- Crea las tablas de Flashcards (repetición espaciada estilo Anki) y carga
-- el mazo "Mi baraja" (271 tarjetas) que sustituye a la pestaña "Curiosidades".

create table if not exists public.flashcards (
  id uuid primary key default gen_random_uuid(),
  mazo text not null,
  frontal text not null,
  posterior text not null,
  created_at timestamptz not null default now()
);

alter table public.flashcards enable row level security;
drop policy if exists "flashcards_select" on public.flashcards;
create policy "flashcards_select" on public.flashcards for select using (true);
drop policy if exists "flashcards_insert" on public.flashcards;
create policy "flashcards_insert" on public.flashcards for insert with check (true);

-- Progreso de repaso por persona y tarjeta (algoritmo SM-2, como Anki):
-- ease_factor = "facilidad" de la tarjeta (empieza en 2.5, sube o baja según
-- lo fácil/difícil que la marque la persona cada vez); intervalo_dias = cada
-- cuántos días toca repasarla; proxima_revision = próxima fecha en la que
-- volverá a aparecer como pendiente.
create table if not exists public.flashcards_progreso (
  name text not null,
  flashcard_id uuid not null references public.flashcards(id) on delete cascade,
  ease_factor numeric not null default 2.5,
  intervalo_dias integer not null default 0,
  repeticiones integer not null default 0,
  proxima_revision date,
  ultima_revision timestamptz,
  updated_at timestamptz not null default now(),
  primary key (name, flashcard_id)
);

alter table public.flashcards_progreso enable row level security;
drop policy if exists "flashcards_progreso_select" on public.flashcards_progreso;
create policy "flashcards_progreso_select" on public.flashcards_progreso for select using (true);
drop policy if exists "flashcards_progreso_insert" on public.flashcards_progreso;
create policy "flashcards_progreso_insert" on public.flashcards_progreso for insert with check (true);
drop policy if exists "flashcards_progreso_update" on public.flashcards_progreso;
create policy "flashcards_progreso_update" on public.flashcards_progreso for update using (true) with check (true);

-- Tarjetas del mazo "Mi baraja" (271):
insert into public.flashcards (mazo, frontal, posterior) values
  ('Mi baraja', 'Inicio habitual en el trastorno ciclotímico y cómo suele ser el comienzo y el curso', 'Suele darse en la adolescencia o la adultez temprana (a los 6 años y medio en niños), insidioso y persistente'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, INSOMNIO pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Alto afecto negativo'),
  ('Mi baraja', 'Ataque de pánico: Los adolescentes parecen estar ___ (más/menos) dispuestos que los adultos a hablar de sus ataques', 'Menos'),
  ('Mi baraja', 'Tasas anteriores al DSM 5 reflejaban una prevalencia de hasta el ___%, quedando el TAG como el trastorno con ___ (posición) mayor prevalencia de entre los trastornos de ansiedad, sólo superado por la Fobia Específica.', '5%, segunda'),
  ('Mi baraja', 'Trastorno psicótico breve: Belloch, Sandín y Ramos (2020) señalan que aproximadamente un ___ % de los casos pueden evolucionar hacia un ___ (trastorno)', '50%, Trastorno Bipolar'),
  ('Mi baraja', 'Trastorno psicótico breve: La proporción entre géneros se sitúa en ___, siendo los/las varones/mujeres los/las que presentan una sintomatología más similar a la de la esquizofrenia', 'Dos mujeres por cada hombre, hombre'),
  ('Mi baraja', 'Las personas con Fobia Específica presentan un ___% más de probabilidad de intentos de suicidio. Este hecho podría deberse a la comorbilidad de las Fobias Específicas con Trastornos de la Personalidad y otros trastornos de ansiedad.', '60%'),
  ('Mi baraja', '% de riesgo para la intencionalidad autolítica en pacientes con trastorno bipolar I i II', '36,3% (I), 32,4% (II)'),
  ('Mi baraja', 'TDM: Se conocen algunas diferencias por edad en cuanto a la presentación sintomatológica: la ___ y la ___ son más probables en los sujetos jóvenes, y los síntomas melancólicos, sobre todo las alteraciones ___, son más frecuentes en los sujetos mayores.', 'Hipersomnia, hiperfagia, psicomotoras'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, BAJA AUTOESTIMA pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Alto afecto negativo'),
  ('Mi baraja', 'La Ciclotimia se puede confundir con algunos Trastornos de la Personalidad, especialmente aquellos en los que también hay cambios de humor bruscos o frecuentes, como en la personalidad ___, ___ y ___', 'Histriónica, límite, antisocial'),
  ('Mi baraja', 'En los ___ (niños/adultos) es más fácil diagnosticar las compulsiones porque suelen son observables, si bien la mayoría de los sujetos afectados por TOC presentan tanto obsesiones como compulsiones.', 'niños'),
  ('Mi baraja', 'Trastorno psicótico breve: El DSM 5 apunta a factores de riesgo temperamentales,
como la presencia de rasgos preexistentes de ___________ pueden predisponer al desarrollo del Trastorno psicótico breve. Por ejemplo rasgos ___ , _______ o rasgos del dominio psicótico (___) o del dominio de afectividad negativa (___).', 'Personalidad, esquizotípicos, limites desregulación perceptiva, suspicacia'),
  ('Mi baraja', 'Esquizofreniforme: En países desarrollados, la incidencia es hasta ___ (número) veces más alta/baja que esquizofrenia; y en países en vías de desarrollo,
la incidencia puede ser ___ (mayor/menor) a la de la esquizofrenia', '5, alta, mayor'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, INESTABILIDAD pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Hiperactivación fisiológica'),
  ('Mi baraja', 'Suicidio: En la esquizofrenia, la muerte por suicidio se produce típicamente durante las fases ___', 'Tempranas'),
  ('Mi baraja', 'Trastorno bipolar II: La tasa de incidencia a los 3 años en mayores de 60 años es del ___%', '0,34%'),
  ('Mi baraja', '% casos distimia que acaban en depresion mayor', '25%'),
  ('Mi baraja', 'TOC: La APA (2013) señala una edad media de inicio es de ___ años. Un ___% de los casos comienza antes de los 14 años y es raro después de los 35 años.  Otras fuentes bibliográficas apuntan a un inicio habitual en una franja que ocupa desde los 18 hasta los 25 años (Belloch, Sandín et al., 2020).', '19,5 años, 25%'),
  ('Mi baraja', 'Trastorno bipolar I:  Cuanto ___ (más/menos) tiempo transcurre el sujeto sin tratamiento, ___ (mejor/peor) es el pronóstico', 'Más, peor'),
  ('Mi baraja', 'El Trastorno Depresivo Persistente tiene a menudo un inicio ____ (Temprano/ tardío) y __ (brusco/ insidioso) y por definición tendrá un curso ___.', 'temprano e insidioso, crónico'),
  ('Mi baraja', 'DSM 5 establece una prevalencia del ___% para el Trastorno
Depresivo Persistente y del ___% para el Trastorno Depresivo
Mayor Crónico', '0,5%, 1,5%'),
  ('Mi baraja', 'Prevalencia trastorno bipolar (incluyendo todos sus subtipos)', '2,4%'),
  ('Mi baraja', 'El síntoma PARESTESIA O ENTUMECIMIENTO forma parte de pánico respiratorio / pánico autonómico / pánico cognitiva', 'Pánico respiratorio'),
  ('Mi baraja', 'TEPT: El DSM-IV-TR incluía un especificador “con inicio demorado” para señalar aquellos casos en los que el inicio de la sintomatología se producía más de ___ meses después del acontecimiento traumático', 'seis'),
  ('Mi baraja', 'La presencia de ataques de pánico nocturnos (despertar del sueño en un estado de pánico) es ___ (frecuente/poco frecuente). Al menos una vez en el ___% de las personas con Trastorno de Pánico, que también suelen tener ataques durante el día.', 'frecuente, 25-33%'),
  ('Mi baraja', 'TDM: El riesgo de recurrencia se vuelve progresivamente ___ (menor/mayor) conforme mayor sea la duración de la remisión. El riesgo es mayor en los pacientes cuyo episodio anterior fue grave, en los sujetos ___ (jóvenes/adultos) (vs. comienzo tardío en Belloch Sandín y Ramos, 2020) y en las personas que han presentado ___ (múltiples episodios/un único episodio). La persistencia de síntomas durante la remisión, aunque siendo leves, es un factor que predice claramente la ____.', 'Menor, jóvenes, múltiples episodios, recurrencia'),
  ('Mi baraja', 'Prevalencia trastorno ciclotímico', '0,4-1%'),
  ('Mi baraja', '___ % TDM causado por factores orgánicos no bien valorados', '10-20%'),
  ('Mi baraja', 'Mayor comorbilidad ciclotímia en niños es ___', 'TDAH'),
  ('Mi baraja', 'Los trastornos bipolares I ¿se dan más en países ricos o pobres?', 'Ricos'),
  ('Mi baraja', 'Alrededor de un__% de los pacientes con AN experimentan depresión mayor a lo largo de la vida.', '66-81'),
  ('Mi baraja', 'Verdadero/Falso TEPT: En relación a los factores de riesgo genéticos y fisiológicos, DSM-5-TR señala que los factores epigenéticos pueden influir en la susceptibilidad a desarrollar un cuadro de TEPT.', 'Verdadero'),
  ('Mi baraja', 'TDM: La probabilidad de los intentos de suicidio disminuye durante la época ___, aunque no el suicidio consumado. Las depresiones de inicio en edades tempranas presentan mayor asociación familiar y es más probable que conlleven asociadas alteraciones de la personalidad', 'Adulta media y tardía'),
  ('Mi baraja', 'Los síntomas ________ pueden seguir presentes en la fase residual, pero normalmente la persona hace crítica de los mismos. Se estima en ___ % la probabilidad de recaída en los ___ primeros años del primer episodio', 'Positivos, 80%, 5 primeros años'),
  ('Mi baraja', 'Riesgo suicidio: El ___-___ % de los pacientes esquizofrénicos fallecen por suicidio', '5-6%'),
  ('Mi baraja', 'El inicio del Trastorno Esquizoafectivo puede darse de manera ___ o ___ a cualquier edad, siendo el inicio típico en la ___. Puede acompañarse de una fase prodrómica en la que son evidentes los síntomas ___.', 'brusca o insidiosa, edad adulta temprana, afectivos'),
  ('Mi baraja', 'TDM: Las mujeres presentan tasas que llegan a ser ___ veces mayores que los hombres.', '1,5-3'),
  ('Mi baraja', 'El desarrollo de un Trastorno de Adaptación se asocia con un/a ____ (aumento/disminución) del rendimiento en el trabajo o escuela y con cambios transitorios en las relaciones sociales. El curso de las enfermedades médicas también puede verse complicado con la ___ (presencia/ausencia) de un Trastorno de Adaptación (p. ej., disminución del cumplimiento terapéutico, aumento de la duración de un ingreso).', 'disminución, presencia'),
  ('Mi baraja', 'Trastorno bipolar I: Los síntomas psicóticos son mucho más frecuentes en la
manía que en la depresión. Aparecen en un ___% de los pacientes, según algunos autores, pudiendo presentarse ideación delirante congruente o no con el estado de ánimo (ideas delirantes de grandeza, místico religiosas, de identidad...).', '75%'),
  ('Mi baraja', 'La Fobia Específica puede iniciarse a cualquier edad, normalmente tras experiencias traumáticas. Lo más frecuente es que se desarrollan en la ___ (período vital), antes de los ___ años, entre los ___ y ___ (siendo la edad media de unos ___ años). Las ___ (tipo de fobias) son las que presentan una edad de inicio más tardía. Los cuadros que se inician en ___ y ___ (períodos vitales) suelen sufrir altibajos durante ese periodo. Los cuadros que persisten en la ___ (período vital) no suelen remitir. Caballo, Salazar y Carrobles (2024) mencionan que la base sobre la que se apoyan las fobias, es decir, el miedo, podría ser señal de un correcto desarrollo cognitivo.', 'primera infancia, 10 años, 7 y los 11, 10 años, fobias situacionales, la infancia y la adolescencia, edad adulta'),
  ('Mi baraja', 'El ___ % de las personas que tienen esquizofrenia tienen alucinaciones multimodales', '30'),
  ('Mi baraja', 'Trastorno de acumulación: La aparición de síntomas es casi ___ veces más frecuente en adultos mayores (55-94 años) que en jóvenes.', '3'),
  ('Mi baraja', 'La prevalencia de TEPT es mayor en ___ (hombres/mujeres) durante toda la vida, ¿y la incidencia la duración de la sintomatología propia del trastorno? DSM-5-TR describe una prevalencia en ___ (hombres/mujeres) entre el 8% y el 11% y entre el 4,1% y el 5,4% para ___ (hombres/mujeres).', 'mujeres, mujeres, mujeres, hombres'),
  ('Mi baraja', 'Incidencia trastorno de desregulación disruptiva del estado de ánimo', 'Tasas mayores en los hombres y los niños en edad escolar que en las mujeres y los adolescentes'),
  ('Mi baraja', 'TEPT: Los eventos traumáticos como el abuso sexual infantil (ASI) aumentan el riesgo de suicidio. El TEPT está asociado con ___ e ___.', 'ideación suicida e intentos de suicidio'),
  ('Mi baraja', 'Verdadero/Falso en relación a esquizofreniforme: Se asume una incidencia similar a la de la esquizofrenia', 'Verdadero'),
  ('Mi baraja', 'Prevalencia del trastorno de desregulación disruptiva del estado de ánimo', '2-5%'),
  ('Mi baraja', 'Agorafobia: La máxima incidencia se da en la ___ y ___.', 'adolescencia tardía y adultez temprana'),
  ('Mi baraja', 'Fobia Específica: Se observan diferencias culturales en prevalencias según ___, ___ y ___.', 'el contenido de la fobia, la edad de inicio y diferente frecuencia por género'),
  ('Mi baraja', 'El Trastorno Dismórfico Corporal parece tener un curso ___, aunque puede mejorar con tratamiento.', 'crónico'),
  ('Mi baraja', 'Ataques de pánico: La edad media de inicio es a los ___ años. El inicio puede
estar influido por el curso de cualquier otro trastorno mental y por la existencia de eventos estresantes.', '22-23 años'),
  ('Mi baraja', 'Un ___ % de las personas con TOC también presenta un trastorno por tics a lo largo de su vida. En niños, puede darse la tríada TOC, ___ y ___.', '30%, Tics, TDAH'),
  ('Mi baraja', 'Bipolar I: % cicladores rápidos', '5-10%'),
  ('Mi baraja', 'Crisis de angustia o ataque de pánico: La duración media suele oscilar en torno a los ___ minutos, pero pueden llegar hasta ___ o ___ horas o incluso más', '30, 1 o 2'),
  ('Mi baraja', 'Ciclotímico: El ___ % acaba convirtiéndose en un trastorno bipolar I o II', '33%'),
  ('Mi baraja', 'El síntoma NÁUSEAS O MALESTAR EN EL ESTÓMAGO forma parte de pánico respiratorio / pánico autonómico / pánico cognitiva', 'Pánico cognitivo'),
  ('Mi baraja', 'Otros factores de riesgo suicidio', 'Síntomas depresivos o desesperanza, situación de desempleo, estar en el periodo posterior a un episodio agudo, o tras el alta hospitalaria de un ingreso'),
  ('Mi baraja', 'Trastorno depresivo persistente: El comienzo temprano (antes de los 21 años) se asocia a ___', 'Mayor probabilidad de cuadros comórbidos de la personalidad y de abuso de sustancias'),
  ('Mi baraja', 'Incidencia trastorno esquizoafectivo', 'Superior en mujeres'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, ALTA ACTIVACIÓN SIMPÁTICA pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Hiperactivación fisiológica'),
  ('Mi baraja', 'Prevalencia trastorno bipolar II', '0,3%'),
  ('Mi baraja', 'TDC: ___ (porción) de los sujetos diagnosticados presentan un inicio del cuadro antes de 18 años. El inicio temprano se asocia a mayor riesgo de ___ y ___.', 'Dos tercios, intentos de suicidio y mayor comorbilidad'),
  ('Mi baraja', 'Los adolescentes pueden están (más/menos) preocupados por los ataques de pánico que los adultos, aunque la presentación clínica es ___ (igual/menor) que en los adultos.', 'menos, igual'),
  ('Mi baraja', 'Pronóstico trastorno psicótico breve, en cuanto a funcionamiento social y sintomatología es ______ para la mayoría de los individuos, con altas/ bajas tasas de recaída', 'Excelente, altas'),
  ('Mi baraja', 'Trastorno de acumulación: Algunos estudios indican que, en población general, la prevalencia es significativamente mayor en los/as ___ (hombres/mujeres). Este dato contrasta con los datos encontrados en muestras clínicas, que se hayan predominantemente formadas por ___ (hombres/mujeres).', 'hombres, mujeres'),
  ('Mi baraja', 'Crisis de angustia o ataque de pánico: Gran aumento de la actividad autónoma ___ (simpática/parasimpática), aunque los cambios fisiológicos no difieren de los acontecidos en la realización de otras actividades como el ejercicio físico.', 'Simpática'),
  ('Mi baraja', 'Crisis de angustia o ataque de pánico: La manifestación de palpitaciones, vértigos (inestabilidad, mareos) y temblores parecen ser los síntomas somáticos que ocurren con más frecuencia durante los ataques de pánico
(>___%)', '>80%'),
  ('Mi baraja', 'La Agorafobia provoca deficiencia y discapacidad funcional, menor productividad laboral y mayor número de días de incapacidad. ___ (porción) de los pacientes puede permanecer completamente confinado en casa.', 'Un tercio'),
  ('Mi baraja', 'Prevalencia en adultos en población general ataques de pánico', '11,2%'),
  ('Mi baraja', 'Verdadero/Falso de la ansiedad social: Suele ocurrir de manera aislada.', 'Falso: Raramente ocurre de manera aislada. La comorbilidad más habitual la encontramos con: otros trastornos de ansiedad, trastorno depresivo mayor, trastornos por consumo de sustancias psicoactivas con la finalidad de atenuar los síntomas (el Trastorno de Ansiedad Social generalmente precede a la aparición de estos cuadros, excepto a la Fobia Específica y el Trastorno de Ansiedad por Separación), trastorno dismórfico corporal, trastorno bipolar y trastorno evitativo de la personalidad (la forma más generalizada de trastorno de ansiedad social, no “sólo actuación”). En niños puede haber autismo de alto funcionamiento y mutismo selectivo.'),
  ('Mi baraja', 'Trastorno esquizoafectivo prevalencia', '0,3%'),
  ('Mi baraja', 'Inicio trastorno de ideas delirantes persistentes (insidioso/ brusco)', 'Insidioso (años)'),
  ('Mi baraja', 'Verdadero/Falso: Se han encontrado variaciones según raza, etnia, país y origen geográfico en inmigrantes e hijos inmigrantes', 'Verdadero'),
  ('Mi baraja', 'Trastorno de desregulación disruptiva del estado de ánimo: ___ (si/no) aparece exclusivamente durante el curso de un Trastorno depresivo mayor y ___ (si/no) se explica mejor por la presencia de otro trastorno mental.', 'No, no'),
  ('Mi baraja', 'Ansiedad social: En Estados Unidos se ha hallado una prevalencia del ___%,
mientras que en Europa las tasas se sitúan en torno al ___%.', '7%, 2,3%'),
  ('Mi baraja', 'En cuanto a los factores de riesgo y pronóstico para el TEPT, DSM-5-TR amplía los factores ___ y hace referencia a que el rasgo de impulsividad premórbido tiende a asociarse con manifestaciones externalizantes del TEPT y comorbilidades del espectro externalizante, incluido el Trastorno por uso de sustancias o el comportamiento agresivo.', 'temperamentales'),
  ('Mi baraja', 'El curso de la Agorafobia es persistente y crónico. Sólo el ___% tendría una remisión completa.', '10%'),
  ('Mi baraja', 'Entre los cambios de la CIE 11 respecto a los trastornos de ansiedad, ¿en qué trastorno NO se menciona el criterio temporal?:', 'Trastorno de pánico'),
  ('Mi baraja', 'Duración trastorno mixto de ansiedad y depresión (CIE 11)', 'La mayor parte de los días, durante al menos 2 semanas'),
  ('Mi baraja', 'TEPT: Muchas personas permanecen sintomáticas durante más de ___ meses y en ocasiones hasta más de ___ años (especificador TEPT crónico, en DSM-IV-TR). Si hay malos tratos físicos y/o psicológicos, normalmente se genera un TEPT ___.', '12, 50, crónico'),
  ('Mi baraja', 'Ataques de pánico: En niños y personas mayores, la prevalencia es ___ (alta/baja)', 'Baja'),
  ('Mi baraja', 'Verdadero/Falso: El comienzo de la Tricotilomanía no tiene nada que ver con la pubertad.', 'Falso: El comienzo de la Tricotilomanía suele coincidir con la pubertad.'),
  ('Mi baraja', 'Verdadero/Falso: Los pensamientos intrusivos en el TOC no suelen tener que ver con eventos traumáticos', 'Verdadero'),
  ('Mi baraja', 'El TAG presenta ___ (mayor/menor) comorbilidad con otros trastornos de ansiedad y trastornos del estado de ánimo, y ___ (mayor/menor) comorbilidad con trastornos por consumo de sustancias, trastornos de conducta, trastornos psicóticos, trastornos del neurodesarrollo y trastornos neurocognitivos.', 'mayor, menor'),
  ('Mi baraja', 'Aproximadamente el ___% de las personas con Trastorno por Acumulación también tiene un trastorno del estado de ánimo o de ansiedad comórbido. Un ___% puede cumplir criterios para TOC. A menudo las comorbilidades son el principal motivo de consulta.', '75%, 20%'),
  ('Mi baraja', 'Los patrones de trastornos comórbidos en Agorafobia son distintos en hombres y mujeres. Los/as ___ (hombres/mujeres) presentan ___ (mayor/menor) comorbilidad con trastornos por consumo de sustancias', 'hombres, mayor'),
  ('Mi baraja', 'Trastorno estrés agudo: La prevalencia varía según la naturaleza del evento y el contexto. La probabilidad de desarrollar este trastorno aumenta a medida que aumenta la intensidad del estresor y la proximidad física al mismo. Las tasas más altas (entre un ___ - ___%) las encontramos vinculadas con eventos traumáticos interpersonales (p. ej., asalto, violación o tiroteo masivo). En eventos traumáticos no interpersonales, encontramos tasas de prevalencia menores al ___%', '20-50%, 20%'),
  ('Mi baraja', 'Trastorno depresivo persistente (distimia): Inicio tardío a partir de los ___ años', '21'),
  ('Mi baraja', 'DSM 5 apunta a la presencia de factores de riesgo genéticos y fisiológicos, señalando mayor riesgo entre familiares de primer grado de pacientes con _______, Trastorno _____ o
Trastorno _____', 'Esquizofrenia, Bipolar, Esquizoafectivo'),
  ('Mi baraja', 'El TOC de inicio temprano en general se caracteriza por peor respuesta a los ___ (clases de antidepresivos 2a generación), ___ (mayor/menor) tasa de sintomatología, ___ (mayor/menor) gravedad, ___ (mayor/menor) presencia de compulsiones sin obsesiones y ___ (mayor/menor) comorbilidad con otros trastornos (Tics, TDAH y Trastornos de Ansiedad).', 'ISRS, mayor, mayor, mayor, mayor'),
  ('Mi baraja', 'El riesgo de desarrollo de TEPT varía en función de los distintos grupos culturales (p.ej., genocidios, estrés de aculturación entre los inmigrantes). La evaluación completa de las expresiones del TEPT en cada zona debe incluir una valoración de ___.', 'la diversidad cultural de los conceptos de peligro'),
  ('Mi baraja', 'En relación a trastorno ciclotímico: Dentro de los trastornos del humor, supone el ___ % del total', '3-5%'),
  ('Mi baraja', 'TDM: En los sujetos de entre 18 y 29 años es hasta __ veces mayor que en los pacientes de 60 años o mayores.', '3'),
  ('Mi baraja', 'En hombres, ¿qué manifestaciones sintomatológicas son más frecuentes?', 'Los síntomas negativos y una duración mayor del trastorno'),
  ('Mi baraja', 'TDC: Las tasas de ideación suicida e intentos de suicidio son altas, principalmente por las preocupaciones sobre la apariencia. Hay alto riesgo de suicidio consumado y elevadas cifras de ___ (tarstorno) comórbido.', 'Trastorno Depresivo Mayor'),
  ('Mi baraja', 'Normalmente, un paciente con Trastorno Ciclotímico presenta períodos breves (entre ___ y ___ días) con sintomatología depresiva y euforia alternantes.', '2 y 6 días'),
  ('Mi baraja', 'Trastorno delirante prevalencia', '0,2%'),
  ('Mi baraja', 'El trastorno cliclotímico puede presentar comorbilidad con _____ y _____', 'Trastorno por consumo de sustancias y trastorno del sueño vigilia'),
  ('Mi baraja', 'En la National Comorbidity Survey de Kessler y cols., 1994), los datos apuntan al ___-___%, lo que muestra que la Fobia Específica es el trastorno por ansiedad ___ (más/menos) prevalente y el ___ (más/menos) prevalente también como ___ (posición) diagnóstico concurrente a otros trastornos de ansiedad.', '10-11%, más, más, segundo'),
  ('Mi baraja', 'Subtipo más frecuente de trastorno delirante es el ___ y la aparición del
tipo celotípico es más frecuente en ___ que en ___.', 'persecutorio, varones, mujeres'),
  ('Mi baraja', 'Trastorno bipolar. Las alucinaciones tienden a ser más frecuentes en la fase de ___', 'mania'),
  ('Mi baraja', 'Trastornos afectivos: Cronicidad: Criterios diagnósticos plenos mantenidos durante más de ___ años seguidos', '2'),
  ('Mi baraja', 'Prevalencia trastorno psicótico breve: Se trata de un cuadro ___ frecuente, más habitual en países ___. DSM 5 no aporta datos de prevalencia en población general, sólo indica que supone el ___ % de los primeros episodios psicóticos en Estados Unidos. Según el DSM-5-TR, el Trastorno psicótico breve puede alcanzar del ___ % al ___% de los casos de psicosis en varios países.', 'Poco, en vías de desarrollo, 9%, 2% al 7%'),
  ('Mi baraja', 'En qué apartado se incluye el trastorno mixto de ansiedad y depresión en la CIE 11', 'Trastorno del estado de ánimo'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, SENTIMIENTOS DE INFERIORIDAD pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Alto afecto negativo'),
  ('Mi baraja', 'Trastorno delirante incidencia', 'Igual en hombres y mujeres'),
  ('Mi baraja', 'Verdadero/Falso TEPT: Los sucesos traumáticos más frecuentes en hombres son: violación, guerra, abandono infantil y abusos en la infancia. Los sucesos traumáticos más frecuentes en mujeres son: violación, acoso sexual, ataques físicos, ser amenazadas con un arma y abusos en la infancia.', 'Verdadero'),
  ('Mi baraja', 'El duelo patológico puede afectar al ___% de las personas allegadas al fallecido. Según DSM-5-TR, esta afectación puede manifestarse en forma de Depresión mayor en personas vulnerables, como Trastorno adaptativo con e___ de a___ d___ y, a modo de novedad en el DSM-5-TR, como T___ de d___ p___ (cuando las reacciones severas persisten al menos 12 meses en adultos o 6 meses en niños y adolescentes). Además, se puede especificar como duelo t___en caso de personas que han sufrido suicidio u homicidio.', '2%, estado de ánimo deprimido, Trastorno de duelo prolongado, traumático'),
  ('Mi baraja', 'Algunos estudios establecen datos de comorbilidad de Trastorno de adaptación y Trastornos de la Personalidad entre el ___ y el ___%.', '15 y el 73%'),
  ('Mi baraja', 'Trastornos de Adaptación: la sintomatología comienza dentro de los ___
meses de inicio de un factor de estrés (dentro del primer mes, según CIE) y no dura más de ___ meses después de haber cesado el agente estresante o sus consecuencias.', 'tres, seis'),
  ('Mi baraja', 'A diferencia de los trastornos depresivos recurrentes, en el Trastorno Bipolar tipo I no es común la presencia de episodios maníacos recurrentes (sólo el ___% de los sujetos con este trastorno presentan exclusivamente episodios de manía', '20%'),
  ('Mi baraja', 'Trastorno de excoriación: El cuadro suele tener inicio en la ___ (período vital), coincidiendo con el inicio de la ___ (proceso de madurez sexual). Comienza con frecuencia con la manipulación del acné propio de esta etapa vital.', 'adolescencia, pubertad'),
  ('Mi baraja', 'TOC: Tradicionalmente, se consideraba que la incidencia era similar en ambos sexos, aunque en los últimos estudios la incidencia encontrada ha sido ligeramente superior en los/as ___ (hombres/mujeres). Además, los/as ___ (hombres/mujeres) están ligeramente más afectadas en la edad adulta y los/as ___ (hombres/mujeres), más afectados en la infancia.', 'mujeres, mujeres, hombres'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, BAJA CONCENTRACIÓN pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Alto afecto negativo'),
  ('Mi baraja', 'Trastorno de acumulación: Los primeros síntomas aparecen en torno a los ___-___ años, interfieren a los ___ años y aparece deterioro clínicamente significativo a mediados de los ___ años.', '11-15 años, 20 años, 30 años'),
  ('Mi baraja', 'La prevalencia del TAG en adolescentes es del ___% y en adultos del ___%. El riesgo a lo largo de la vida se estima en un ___%.', '0,9%, 2,9%, 9%'),
  ('Mi baraja', 'El TAG suele presentar un curso ___ y ___, con (altas/bajas) tasas de remisión completa', 'crónico y oscilante, bajas'),
  ('Mi baraja', 'Suicidio: Hasta el ___% de los suicidios ocurren durante los primeros tres años de enfermedad, y prácticamente la totalidad entre el establecimiento del diagnóstico y los siete años de evolución', '70%'),
  ('Mi baraja', 'Trastorno bipolar. Los delirios tienden a ser más frecuentes en la fase de ___', 'depresión'),
  ('Mi baraja', 'TOC: Se estima una prevalencia del ___% en Estados Unidos y del ___ - ___% a nivel internacional', '1,2%, 1,1-1,8%'),
  ('Mi baraja', 'Tricotilomanía: Las mujeres se ven más afectadas, con una ratio de ___ mujeres por cada hombre. Esta desigualdad puede reflejar diferencias en la búsqueda de tratamiento según el género. En los niños, varones y mujeres la incidencia es', '10 mujeres por cada hombre, igual'),
  ('Mi baraja', 'Trastorno psicótico breve: Suele tener un inicio ___, con frecuencia vinculado a desencadenante de estrés. Puede aparecer en cualquier momento de la vida, sobre todo en ___, con una edad media de inicio de ___ años', 'Brusco (sin pródromos), adolescencia o principio de edad adulta, 30'),
  ('Mi baraja', 'Según DSM 5, se establecen datos de prevalencia para la Fobia Específica de un ___% en población general, un ___% en niños, un ___% en adolescentes (___ años) y un ___% en personas mayores.', '7-9%, 5%, 16%, 13-17 años, 3-5%'),
  ('Mi baraja', 'El riesgo de suicidio en el Trastorno Bipolar es de _ a _ veces superior al de la población general', '20, 30'),
  ('Mi baraja', 'Trastorno estrés agudo: Los síntomas empiezan normalmente inmediatamente tras el trauma, pero es necesario que persistan al menos durante ___ días y hasta un máximo de ___ mes/meses para cumplir los criterios del trastorno', '3 días, 1 mes'),
  ('Mi baraja', 'Trastorno bipolar I: sSgún DSM 5, más del ___% de los pacientes que tienen un único episodio maníaco presenta recurrencia', '90%'),
  ('Mi baraja', 'TDM: El principal factor de riesgo de suicidio son los ___ o ___, pero no se debe ignorar que la mayoría de los suicidios consumados NO se han precedido de intentos fallidos', 'Antecedentes de intentos, amenazas de suicidio'),
  ('Mi baraja', 'La mayoría de los pacientes __-__ % presentan una fase premórbida que tiene una duración media de ___ años', '80-90%, 5 años.'),
  ('Mi baraja', 'La edad media de inicio del Trastorno de Pánico es a los ___ años. Son poco frecuentes el inicio en la ___ (infancia/adolescencia) y después de los ___ años. En estudios recientes se encontró que la prevalencia más alta de Ataque de Pánico y Trastorno de Pánico se situaba entre aquellas personas con edades comprendidas entre los ___ años y los ___ años, mientras que las tasas más bajas se hallaban en las personas de mayor edad (mayores de ___ años).', '20 -24 años, infancia, 45 años, 30-39 años, 40-49 años, 80 años'),
  ('Mi baraja', 'En relación al trastorno ciclotímico: Existe un riesgo del ___ % de desarrollar posteriormente un Trastorno Bipolar I o II, por lo que se considera para algunos autores un reflejo de una predisposición temperamental a otros
Trastornos Bipolares', '15-50%'),
  ('Mi baraja', 'El riesgo de desarrollar un TEPT tras una agresión sexual es ___ (mayor/menor) si el agresor es una persona conocida de la víctima y pertenece a su entorno de confianza.', 'mayor'),
  ('Mi baraja', 'Trastorno de ideas delirantes persistentes: Frecuencia alucinaciones y tipo/s más frecuente/s', 'Raras, táctiles u olfativas'),
  ('Mi baraja', 'Los Trastornos de Adaptación son trastornos comunes. La prevalencia varía en función de la población estudiada: ___-___% de los individuos en tratamiento ambulatorio de salud mental, alcanzando hasta el ___% en entorno de consulta psiquiátrica hospitalaria (siendo el diagnóstico más común).', '5-20%, 50%'),
  ('Mi baraja', 'TEPT: Factores que influyen en la presencia de mayores tasas de prevalencia en ____ (hombres/mujeres) son la mayor probabilidad de exposición a eventos traumáticos en ____ (hombres/mujeres) en comparación con ____ (hombres/mujeres) (violación, violencia interpersonal). En poblaciones expuestas específicamente a estos tipos de estrés, las diferencias de género ___ (sí/no) son significativas.', 'mujeres, mujeres, hombres, no'),
  ('Mi baraja', 'TEPT: Los síntomas generalmente comienzan dentro de los ___ primeros meses después del acontecimiento traumático, aunque el debut de los síntomas puede demorarse mucho tiempo, incluso ___ (meses/años).', 'tres, años'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, INHIBICIÓN PSICOMOTORA pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Bajo afecto positivo'),
  ('Mi baraja', 'El Trastorno Depresivo Mayor puede aparecer por primera vez a ___', 'Cualquier edad'),
  ('Mi baraja', 'El ___ % de las personas que han tenido un episodio depresivo mayor desarrollarán un episodio maníaco o hipomaníaco y cambiarán el diagnóstico de trastorno depresivo mayor a trastorno bipolar I o II.', '10-13%'),
  ('Mi baraja', 'En el especificador "con asiedad" para trastornos depresivos, el grado de gravedad actual grave se necesita ___ síntomas y con ___', 'cuatro o cinco, agitación motora'),
  ('Mi baraja', 'Un _% de las familias de los pacientes con AN presenta al menos un miembro con un tno alimentario clínico o subclínico', '24,3'),
  ('Mi baraja', 'Prevalencia esquizofrenia', '0,3-0,7%'),
  ('Mi baraja', 'TEPT: DSM-5-TR añade otros factores que probablemente influyen en las mayores tasas de prevalencia en mujeres: ___, y ___.', 'las diferencias de género en el procesamiento emocional y cognitivo del trauma, y los efectos de las hormonas reproductivas.'),
  ('Mi baraja', 'El Trastorno de Pánico presenta una prevalencia del ___% en adultos y adolescentes. La prevalencia es ___ (alta/baja) antes de los 14 años (___%) y en personas mayores (___%).', '2-3%, baja, <0,4%, 0,7%'),
  ('Mi baraja', 'Si el cuadro clínico se inicia más tarde de los ___ años, el DSM lo considera ____, aunque la edad media de aparición de la esquizofrenia de inicio tardío se encuentre en torno a los ___ años', '40 años, esquizofrenia de inicio tardío, 60 años'),
  ('Mi baraja', 'TDC: La prevalencia de este trastorno es mayor entre la población que se somete a procedimientos de cirugía estética (___-___%), oral o maxilofacial (___%).', '3-16%, 10%'),
  ('Mi baraja', 'Trastorno bipolar II: Sobre las consecuencias funcionales, aunque muchos pacientes vuelven a un nivel completo de funcionamiento interepisódico, en un ___% persiste algún tipo de disfunción y un ___% pasa directamente a otro episodio afectivo sin período de recuperación.', '15%, 20%'),
  ('Mi baraja', 'Ansiedad social: En un ___ % de los casos, los síntomas remiten en 1 año y en un ___ % remiten en unos pocos años. En un ___ % de los casos, sin tratamiento específico, el curso puede extenderse varios años.', '30%, 50%, 60%'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, AGITACIÓN PSICOMOTORA pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Alto afecto negativo'),
  ('Mi baraja', '% en la desorganización del habla y del pensamiento en esquizofrenia, manía, depresión y trastornos de la personalidad (los 4 tienen diferente %)', '50-80, >70, >50 y en torno al 35.'),
  ('Mi baraja', 'Prevalencia TDM', '7%'),
  ('Mi baraja', 'Trastorno depresivo persistente (distimia): Inicio temprano antes de los ___ años', '21'),
  ('Mi baraja', 'El trastorno esquizoafectivo presenta un patron temporal/ diversos patrones temporales. Lo más habitual es que el curso sea breve/ prolongado y episódico con remisiones. En general, presenta una progresión mejor que la ___, pero peor que los ___.', 'patrones temporales, prolongado, Esquizofrenia, cuadros afectivos'),
  ('Mi baraja', 'Se estima una prevalencia aproximada del ___-___% para el Trastorno por Acumulación, aunque no se dispone de estudios concluyentes. DSM-5-TR establece que en Estados Unidos y Europa la prevalencia oscila entre el ___% y el ___%', '2-6%, 1,5% y el 6%'),
  ('Mi baraja', 'Las consecuencias funcionales del trastorno esquizoafectivo son ___. El funcionamiento suele estar afectado, aunque ___', 'Muy variables, no es criterio diagnóstico'),
  ('Mi baraja', 'El intervalo interepisódico tiende a reducirse con la edad, presentando un ___% de las personas con Trastorno Bipolar II múltiples episodios del estado de ánimo en el último año y considerándose cicladores rápidos', '5-15%'),
  ('Mi baraja', 'La edad media de inicio del Trastorno Bipolar II es de ____ años (ligeramente más tardía que el Trastorno Bipolar I y más temprana que el Trastorno Depresivo Mayor) y suele comenzar con un episodio ____, no reconociéndose como Trastorno Bipolar II hasta que aparece un episodio hipomaníaco (cosa que sucede en un ___% de los pacientes con diagnóstico inicial de Trastorno Depresivo Mayor). Pueden precederle ansiedad, abuso de sustancias y trastornos de conducta alimentaria, lo que ____ (facilita/dificulta) su detección', '25 años, depresivo,12%, dificulta'),
  ('Mi baraja', 'Según DSM 5, en población general, el Trastorno de Excoriación tiene una prevalencia del ___%. Según DSM-5-TR, en un estudio de 10000 adultos, se encontró que el ___% se identificó con un Trastorno de Excoriación actual y el ___% informó un Trastorno de Excoriación de por vida.', '1,4%, 2,1%, 3,1%'),
  ('Mi baraja', 'Se trata de un cuadro más prevalente en ___ que en ___ (2:1). La diferenciación por géneros se produce en la ___(niñez/adolescencia) (es observable antes de los ___ años), momento en que se produce un aumento gradual de los casos, especialmente en los/as ___, alcanzando un máximo durante la ___ (adolescencia/edad adulta/vejez).', 'mujeres, hombres, adolescencia, 14 años, mujeres, edad adulta'),
  ('Mi baraja', 'El ___ % de las personas que tienen esquizofrenia tienen alucinaciones auditivas', '79'),
  ('Mi baraja', 'Edad media de inicio del primer episodio afectivo en trastorno bipolar I', 'Aprox 18 años. ¡AUNQUE EL COMIENZO PUEDE DARSE A LO LARGO DE TODO EL CICLO VITAL, INCLUSO PUEDEN APARECER CUADROS INICIALES A LOS 60-70 AÑOS¡'),
  ('Mi baraja', 'En esquizofrenia el ___ % tiene alucinaciones', '80'),
  ('Mi baraja', 'Trastorno delirante: Aunque puede aparecer en adultos ______, suele ser más prevalente en ___', 'jovenes, individuos mayores (35-55 años)'),
  ('Mi baraja', '¿Cuál es el especificador del trastorno ciclotímico?', 'Con ansiedad'),
  ('Mi baraja', 'Los síntomas positivos mejoran +/- con el tiempo que los síntomas negativos', '+'),
  ('Mi baraja', 'Según DSM 5, el riesgo de suicidio es ___ (mayor/menor) en el Trastorno Bipolar II y los intentos son más letales. ___ (porción) de los pacientes refiere antecedentes de intento de suicidio.
DSM-5-TR dice que tanto el riesgo y la incidencia de intentos de suicidio, como las tasas de suicidio consumado parecen ser ___ (similares/distintas) en el trastorno bipolar I y en el trastorno bipolar II.', 'Mayor, un tercio, similares'),
  ('Mi baraja', 'En trastornos esquizoafectivos se calcula un riesgo de suicidio del ___ % siendo el principal factor de riesgo para el suicidio la presencia de síntomas _____', '5%, depresivos'),
  ('Mi baraja', 'Bipolar II: Solo entre el ___ % suele evolucionar a un trastorno bipolar I', '5-15%'),
  ('Mi baraja', 'SQZ. Riesgo suicidio: Un ___ % intenta suicidarse en alguna ocasión', '20%'),
  ('Mi baraja', 'En mujeres, ¿qué manifestaciones sintomatológicas son más frecuentes?', 'Más síntomas afectivos y cuadros breves'),
  ('Mi baraja', 'Agorafobia: El inicio más común (dos tercios de los casos) se da antes de los ___  años. Se han observado dos picos de aparición: en la adolescencia tardía/adultez temprana y después de los ___ años. La edad media de inicio son los ___ años. La edad de inicio si no hay ataques de pánico previos es algo más tardía, en torno a los ___ años.', '35 años, 40 años, 17 años, 25-29 años'),
  ('Mi baraja', '¿Diagnosticos de la CIE 11 que NO incluyen el especificador de instrospección “de regular a buena” o “deficiente o ausente” en el capítulo de trastornos obsesivos compulsivos y otros trastornos relacionados?', 'Trastorno por acumulación y trastorno por comportamiento repetitivo centrado en el cuerpo'),
  ('Mi baraja', 'A largo plazo, padecer Agorafobia se asocia con mayor riesgo de ___, ___ y ___.', 'Trastorno Depresivo Mayor secundario, Trastorno Depresivo Persistente y Trastorno por consumo de sustancias'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, SENTIMIENTOS DE INUTILIDAD pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Bajo afecto positivo'),
  ('Mi baraja', 'DSM 5 sitúa la edad media de inicio del TAG en los ___ años, una edad de inicio más ___ (temprano/tardía) que en otros trastornos de ansiedad. El inicio ___ se asocia a mayor ___ y ___.', '30 años, tardía, precoz, comorbilidad y deterioro'),
  ('Mi baraja', 'Se observa ___ (mayor/menor) prevalencia en mujeres que en hombres (___) (escala numérica), aunque las tasas varían en función del estímulo fóbico: En las Fobias Específicas de los tipos animal, entorno natural y situacional se da un claro predominio en ___ (hombres/mujeres). En la Fobia Específica tipo sangre-inyección-herida, la prevalencia es ___ (diferente/similar) en ambos sexos.', 'mayor, (2:1), mujeres, similar'),
  ('Mi baraja', 'Ansiedad social: Un factor de buen pronóstico es ___.', 'el cumplimiento de las tareas de exposición entre sesiones'),
  ('Mi baraja', 'TDM: El deterioro varía desde ___ o hasta a la ___.', 'Muy ligero, incapacidad completa'),
  ('Mi baraja', 'Trastorno disfórico premenstrual: Se trata de otra categoría de nueva aparición en el DSM 5, que el DSM-IV-TR incluía dentro del ___', 'Trastorno Depresivo No Especificado'),
  ('Mi baraja', 'TEPT: La presencia de sentimientos de ira o culpa se ha demostrado como predictor de ___ (mala/buena) respuesta al tratamiento', 'mala'),
  ('Mi baraja', '¿Los ataques de pánico son mayores en hombres o mujeres?', 'Mayor en mujeres que en hombres (la diferencia será todavía más pronunciada en el Trastorno de Pánico)'),
  ('Mi baraja', 'Prevalencia esquizofreniforme', '0,5-1,5%'),
  ('Mi baraja', 'Si existe ánimo deprimido además de dos o más síntomas de los criterios del episodio depresivo mayor durante dos años o más, entonces se realiza el diagnóstico de ___', 'Trastorno Depresivo Persistente'),
  ('Mi baraja', 'Curso en TDM', 'Muy variable'),
  ('Mi baraja', 'En los episodios maníacos, ¿qué alteración de la sensopercepción se puede dar en un 25% de los casos?:', 'Alucinaciones auditivas'),
  ('Mi baraja', 'Ansiedad social: Los/las ___ (hombres/mujeres) presentan un mayor número de miedos sociales y trastornos depresivos, bipolares y de ansiedad comórbidos. Los/las (hombres/mujeres) presentan en mayor medida miedo a citas, comorbilidad con trastorno negativista desafiante, trastorno de conducta, y uso de alcohol y drogas para aliviar síntomas. La paruresis también tiene una mayor prevalencia de aparición en ___ (hombres/mujeres).', 'mujeres, hombres, hombres'),
  ('Mi baraja', 'Un ___ (porción) del riesgo de sufrir TAG es genético.', 'tercio'),
  ('Mi baraja', 'Edad inicio en hombres segun DSM-5', '20-25 años'),
  ('Mi baraja', 'Normalmente, las personas con Fobia Específica temen a un promedio de tres objetos o situaciones y, en un ___% de los casos, el temor es a más de una situación u objeto.', '75%'),
  ('Mi baraja', 'Un ___% de los adolescentes y adultos son diagnosticados anualmente de Agorafobia. En mayores de ___ años, la prevalencia anual es de un ___%. En el DSM-5-TR se señala una prevalencia que se sitúa entre el ___% y el ___%.', '1,7%, 65 años, 0,4%, 1% y el 1,7%'),
  ('Mi baraja', 'Otro trastorno bipolar y trastorno relacionado especificados (5)', '1. Episodios hipomaníacos de corta duración (2-3 días) y episodios de depresión mayor
2. Episodios hipomaníacos con síntomas insuficientes y episodios de depresión mayor
3. Episodio hipomaníaco sin episodio de depresión mayor previo
4. Ciclotimia de corta duración (menos de 2 años)
5. Episodio maníaco superpuesto a un trastorno psicótico'),
  ('Mi baraja', 'Los ataques de pánico son raros en ___ y ___ (etapa ciclo vital); los adolescentes pueden ser ___ (más/menos) proclives a hablar de ellos que los adultos; en personas mayores puede estar ___ (sobrediagnosticada/infradiagnosticado) debido a su ___ (alta/baja) respuesta del sistema nervioso autónomo comparada con los jóvenes', 'Niños y preadolescentes, menos, infradiagnosticado, baja'),
  ('Mi baraja', 'Los síntomas psicóticos parecen ser ___ (más/menos) frecuentes durante los episodios depresivos del Trastorno Bipolar tipo II que durante los del tipo I', 'Menos'),
  ('Mi baraja', 'TEPT: La mayoría de los estudios sobre violación son con mujeres, aunque se ha estimado que el ___% son hombres y el ___% niños.', '6-10%, 18%'),
  ('Mi baraja', 'Trastorno de Adaptación: Se asocian con un ___ (mayor/menor) riesgo de intentos de suicidio y suicidios consumados; estos con frecuencia están relacionados con c___ con el g___ de a___ p___ y con problemas e___.', 'mayor, conflictos con el grupo de apoyo primario, económicos'),
  ('Mi baraja', 'Trastorno bipolar II: Suele manifestarse junto a al menos otro trastorno mental
(el ___% presenta tres o más).', '60%'),
  ('Mi baraja', 'Un ___% de los sujetos inicialmente diagnosticados de Trastorno Bipolar II acabará cumpliendo criterios para Trastorno Bipolar I (debiéndose cambiar el diagnóstico), ya que desarrollará un episodio maníaco', '5-15%'),
  ('Mi baraja', 'Según DSM-IV, la prevalencia combinada de los Trastornos Bipolares I, II y sin especificar es del ___%', '1,8-2,7%'),
  ('Mi baraja', 'Verdadero/Falso: El Trastorno por Acumulación suele comenzar en etapas tempranas y se extiende hasta las últimas etapas de la vida', 'Verdadero'),
  ('Mi baraja', 'En población general, el ___% de las personas con Agorafobia ha experimentado ataques de pánico o Trastorno de Pánico antes de la aparición de la sintomatología agorafóbica, en comparación con el ___% hallado en población clínica.', '30%, 50%'),
  ('Mi baraja', 'Tricotilomanía: Normalmente, el cuadro presenta un curso ___ y ___. Pueden variar con el tiempo las zonas de donde se arranca el vello. Es frecuente el empeoramiento de la sintomatología en hombres/mujeres acompañando a los cambios hormonales.', 'crónico y fluctuante, mujeres'),
  ('Mi baraja', 'Si no se trata, el TOC suele tener un curso _____, con síntomas oscilantes y fluctuaciones reactivas a acontecimientos estresantes o cambios vitales. Son frecucentes /poco frecuentes las remisiones completas y después de una remisión puede existir recaídas producidas por ___, ___ (con la que presenta gran comorbilidad), ___ u otros factores.', 'crónico, poco frecuentes, ansiedad, depresión, fatiga'),
  ('Mi baraja', 'Formas de evolución esperadas en el trastorno bipolar y el porcentaje asociado a cadauna de ellas', '15% estables, 45% muchas recaídas, 30% sintomatología residual, 10% curso crónico y progresivamente deteriorante'),
  ('Mi baraja', 'La prevalencia de desarrollo del TEPT en población expuesta a agresiones sexuales está en torno al ___%. Estudios incluidos en Caballo, Salazar y Carrobles (2024), señalan prevalencias que pueden alcanzar hasta el ___% de las personas afectadas por violencia o agresiones sexuales', '50%, 50-70%'),
  ('Mi baraja', '___ (número) tercio de los pacientes se recuperan y su diagnóstico se queda como esquizofreniforme, mientras que ___ (número) tercios evolucionan hacia Esquizofrenia o hacia Trastorno Esquizoafectivo', 'Un, dos'),
  ('Mi baraja', 'En relación al trastorno de desregulación disruptiva del estado de ánimo, se producen, de media, al menos ___ veces por semana', '3'),
  ('Mi baraja', 'Prevalencia trastorno disfórico premenstrual', '1,8%-5,8%'),
  ('Mi baraja', 'Tasa prevalencia trastorno bipolar I', '1, 1:1'),
  ('Mi baraja', '¿Cómo son los rítmos circadianos y sueño en episodio depresivo? (menor o mayor)
___ latencia del sueño REM.
___ cantidad de sueño REM.
___ cantidad de sueño profundo', 'Menor, mayor, menor'),
  ('Mi baraja', 'Verdadero/falso: Tener un nivel de autoconciencia bajo es una variable de vulnerabilidad', 'Falso'),
  ('Mi baraja', 'Los/as ___ (hombres/mujeres) tienen un doble de probabilidad de experimentar Agorafobia que los/as ___ (hombres/mujeres).', 'mujeres, hombres'),
  ('Mi baraja', 'Incidencia trastorno ciclotímico', 'Igual en hombres que mujeres. ¡Sin embargo, es más probable que las mujeres acudan a tratamiento, siendo por tanto mayor su prevalencia en mujeres en entornos clínicos!'),
  ('Mi baraja', '____%de los sujetos diagnosticados de TOC van a presentar pensamientos suicidas en algún momento de su vida y un ___ % va a llegar a realizar un intento de suicidio.', '50%, 25%'),
  ('Mi baraja', 'Para el trastorno _______: DSM 5 apunta a la presencia de factores de riesgo genéticos y fisiológicos, señalando que los familiares de estos pacientes tienen un riesgo mayor de padecer esquizofrenia.', 'esquizofreniforme'),
  ('Mi baraja', 'Trastorno de estrés agudo: Los síntomas deben durar entre ___ y ____ tras la exposición al acontecimiento traumático', '3 días y un mes'),
  ('Mi baraja', 'El Trastorno de Ansiedad Social suele aparecer en la ___ (período vital), con una edad media de inicio de ___ años (el 75% tiene una edad entre ___ años). A veces aparece después de ___ o ___ en la infancia. El inicio puede ser ___ o ___. Suele darse tras un ___ o ___.', 'adolescencia, 13 años, 8-15 años, una historia de inhibición social o timidez, brusco o insidioso, acontecimiento estresante o por cambios vitales que exigen nuevas responsabilidades'),
  ('Mi baraja', 'Aproximadamente, al ___-___% de los individuos con Trastorno por Acumulación les es aplicable el especificador con adquisición excesiva; bien sea por compra, por adquisición de artículos gratuitos o por robo (el robo es poco frecuente).', '80-90%'),
  ('Mi baraja', 'La heredabilidad estimada del TAG es de entre el ___ % y el ___%. Se le considera como uno de los trastornos de ansiedad con ___ (mayor/menor) influencia genética', '30%, 40%, menor'),
  ('Mi baraja', 'Encontramos una mayor prevalencia del TAG en mujeres que en hombres ___ (escala numérica) y una mayor prevalencia del TAG en la ___ (período vital), aumentando/disminuyendo en edades más avanzadas. Los datos de prevalencia también son ___ (más/menos) elevados en países desarrollados.', '2:1, edad media, disminuyendo, más'),
  ('Mi baraja', 'TDC: En cuanto a las características clínicas principales del trastorno, hay ___ (más diferencias que similitudes/más similitudes que diferencias) entre hombres y mujeres', 'más similitudes que diferencias'),
  ('Mi baraja', 'Inicio esquizofrenia: ¿rápido o lento?', 'Rápido (meses)'),
  ('Mi baraja', 'Esquizofrenia: Frecuencia alucinaciones y tipo más frecuente', 'Frecuentes y auditivas'),
  ('Mi baraja', 'TDC: La edad media de inicio del trastorno suele estar entre los ___ y los ___años, aunque los primeros síntomas aparecen de manera más temprana, entre los ___-___ años.', '16 y los 17 años, 12-13 años'),
  ('Mi baraja', 'Trastorno psicótico breve: En algunos manuales se señala que lo más habitual es que aparezca en forma de ___ , aunque el DSM 5 habla de una elevada tasa de recaída en este cuadro', 'Episodio único'),
  ('Mi baraja', 'El trastorno esquizoferiforme: suele tener un inicio y resolu-
ción ___, y curso y evolución ___', 'bruscos, similar al de la esquizofrenia'),
  ('Mi baraja', 'Trastorno estrés agudo: No se puede diagnosticar hasta que la sintomatología esté presente al menos durante ___ días. Por definición, la sintomatología debe durar menos de un mes. Si la sintomatología persiste, es posible que la persona afectada cumpla criterios diagnósticos de ___. La mitad de las personas que finalmente desarrollan ___ cumplían inicialmente criterios de TEA.', 'tres, TEPT, TEPT'),
  ('Mi baraja', 'El Trastorno de Pánico es poco frecuente en ausencia de otra psicopatología. Es común la comorbilidad con otros trastornos de ansiedad (especialmente ___), depresión mayor (___%; en ___ -porción- la depresión precede al pánico), trastorno bipolar y trastorno por consumo moderado de alcohol.', 'agorafobia, 10-65%, 1/3'),
  ('Mi baraja', 'Verdadero/Falso TEPT: Los índices más altos de prevalencia se encuentran entre veteranos y otras personas con profesiones de riesgo (p. ej., policías, bomberos, médicos de emergencia); y entre supervivientes de violación, combate militar, cautiverio, internamiento y genocidio.', 'Verdadero'),
  ('Mi baraja', 'El ___ % de las personas que tienen esquizofrenia tienen alucinaciones visuales', '30'),
  ('Mi baraja', '¿Cuáles son los otros trastornos depresivos especificados?', 'Depresión breve recurrente, episodio depresivo de corta duración (4-13 días), y episodio depresivo con síntomas insuficientes'),
  ('Mi baraja', 'trastorno difórico premenstrual: La presencia de los síntomas debe confirmarse con ___ durante al menos ___ ciclos', 'Evaluaciones diarias prospectivas, dos'),
  ('Mi baraja', 'El TAG es más frecuente en ___ (hombres/mujeres). En población clínica en torno al ___ % de las personas afectadas son ___ (hombres/mujeres). En población general se estima que 2/3 son ___ (hombres/mujeres).', 'mujeres, 55-60%, mujeres, mujeres'),
  ('Mi baraja', 'Verdadero/Falso TEPT: Puede ocurrir a cualquier edad.', 'Verdadero'),
  ('Mi baraja', 'Prevalencia mayor entre hombres y mujeres', 'Similar, pero sí se reconocen diferencias en cuanto a las manifestaciones sintomatológicas de la esquizofrenia en unos y en otros'),
  ('Mi baraja', 'Los episodios maníacos con características mixtas suponen el ___ % de los episodios maníacos', '10-20%'),
  ('Mi baraja', 'Verdadero/falso en factores pronóstico en el trastorno bipolar I: mal pronóstico si tiene episodios maníacos breves', 'Falso'),
  ('Mi baraja', 'El síntoma MIEDO A MORIR forma parte de pánico respiratorio / pánico autonómico / pánico cognitiva', 'Pánico respiratorio'),
  ('Mi baraja', 'El trastorno disfórico premenstrual puede aparecer en cualquier momento tras la ___ y muchas de las pacientes indican que los síntomas ___ (mejoran/empeoran) al acercarse la menopausia', 'menarquia, empeoran'),
  ('Mi baraja', 'TDM: La recuperación se inicia normalmente dentro de los ___ meses siguientes al comienzo de los síntomas en ___ (porción) pacientes y en el plazo de ___ (tiempo) en ___ (porción) pacientes', 'Tres, dos de cada cinco, un año, cuatro de cada cinco'),
  ('Mi baraja', 'El  __% de los adultos que padecen TEPT podemos encontrar una recuperación completa de la sintomatología en un plazo de 3 meses', '50'),
  ('Mi baraja', 'La Agorafobia suele acompañarse de periodos de confinamiento en casa. Estas personas suelen depender de los demás para el acceso a diferentes servicios o para la cobertura de necesidades básicas. La ___, los síntomas ___, el ___, y la ___ también son frecuentes', 'desmoralización, los síntomas depresivos, el abuso de alcohol y sedantes, y la automedicación'),
  ('Mi baraja', 'Edad inicio en hombres segun Belloch', '15-24 años'),
  ('Mi baraja', '% Heredabilidad trastorno disfórico premenstrual', '50%'),
  ('Mi baraja', 'Trastorno bipolar I: Aproximadamente el ___% de los episodios maníacos ocurre justo antes de un episodio depresivo mayor.', '60%'),
  ('Mi baraja', 'Existen diferencias de género en la edad de inicio del trastorno, presentando los varones inicio más temprano que las mujeres y, de hecho, casi el ___% de los varones tiene una edad de inicio antes de los 10 años. En los varones, la edad de inicio habitual suele ubicarse en torno a los 6-15 años y en las mujeres, en torno a los 20-29 años. Según DSM-5-TR, alrededor de un ___% de los hombres tienen un comienzo anterior a los 10 años', '25%, 25%'),
  ('Mi baraja', 'Trastorno bipolar I: Según DSM-5, más del ___ % de los pacientes que tienen un único episodio maníaco presenta recurrencia', '90%'),
  ('Mi baraja', 'Trastorno de Excoriación: Tres cuartas partes de los afectados son ___ (hombres/mujeres), lo que puede reflejar diferencias de género en búsqueda de tratamiento.', 'mujeres'),
  ('Mi baraja', 'Edad inicio en mujeres segun Belloch', '15-29 años'),
  ('Mi baraja', 'Edad inicio en mujeres segun DSM 5', '26-30 años'),
  ('Mi baraja', 'En relación al trastorno ciclotímico: Si el inicio de los síntomas se produce en la ___ (momento vital), es importante hacer un diagnóstico diferencial con el Trastorno Bipolar y relacionado debido a otra afección médica', 'Adultez tardía'),
  ('Mi baraja', 'Según datos de DSM-5-TR, las personas con TEPT son un ___% más propensos a presentar síntomas que cumplen criterios para al menos otro trastorno mental (Depresión, Ansiedad, Consumo sustancias, Trastorno Bipolar…)', '80%'),
  ('Mi baraja', 'Suicidio: El ___-___ % de las personas con un primer episodio psicótico ha realizado algún intento de suicidio.', '14-38%'),
  ('Mi baraja', 'En EEUU, la prevalencia del Trastorno Dismórfico Corporal es del ___% (___% en mujeres y ___% en varones). Fuera de EEUU, la prevalencia baja hasta el ___-___%, encontrándose tasas similares en ambos sexos. Según DSM-5-TR, fuera de los Estados Unidos (p. ej., Alemania), estudios similares indican que la prevalencia puntual es del ___% al ___%, sin diferencias entre sexos.', '2,4%, 2,5%, 2,2%, 1,7-1,8%, 1,7% al 2,9%'),
  ('Mi baraja', 'TEPT: Los niños y adolescentes generalmente muestran una prevalencia ___ (mayor/menor), al igual que personas mayores.', 'menor'),
  ('Mi baraja', 'El curso es crónico con oscilaciones. Sólo una minoría alcanza una remisión completa durante años sin ninguna recaída. Habitualmente el curso se complica por comorbilidad con ___, ___ o ___.', 'otros trastornos de ansiedad, depresión o uso de sustancias'),
  ('Mi baraja', 'Verdadero/falso en factores pronóstico en el trastorno bipolar I: mal pronóstico si es de sexo masculino', 'Verdadero'),
  ('Mi baraja', 'En esquizofrenia el ___ % tiene delirios', '45'),
  ('Mi baraja', 'Verdadero/Falso de trastornos delirantes: Estas personas pueden conservar aparente normalidad del comportamiento si no se habla de las ideas delirantes.', 'Verdadero'),
  ('Mi baraja', 'En EEUU, la prevalencia del TEPT es de ___%, estimándose más baja, en torno al ___%, en Europa y otros continentes. DSM-5-TR señala una prevalencia del ___% para los adultos de EEUU, mientras que para los adolescentes estadounidenses la sitúa entre el ___% y el ___%', '3,5%, 0,5-1%, 6,8%, 5% y el 8,1%'),
  ('Mi baraja', 'Prevalencia DURANTE 12 MESES del trastorno bipolar I', '0-0,6%'),
  ('Mi baraja', 'Los ataques de pánico son más frecuentes en ___, si bien las características clínicas ___ (si/no) difieren entre sexos.', 'mujeres, no'),
  ('Mi baraja', 'Verdadero/falso en factores pronóstico en el trastorno bipolar I: buen pronóstico si presenta edad avanzada al inicio de la enfermedad', 'Verdadero'),
  ('Mi baraja', 'X ___ riesgo TDM en familiar de primer grado', '4'),
  ('Mi baraja', 'En población general, se encuentran tasas de prevalencia del ___-___% para la Tricotilomanía, estando los/as ____ (hombres/mujeres) más afectadas que los/as ____ (hombres/mujeres).', '1-2%, mujeres, hombres'),
  ('Mi baraja', 'El __% de estas personas presenta trastornos de ansiedad, porcentaje que se repite para la comorbilidad entre trastorno bipolar tipo II y los trastornos de ansiedad', '75'),
  ('Mi baraja', 'Trastorno de acumulación: Las características generales son comparables entre varones y mujeres, pero los/as ___ (hombres/mujeres) muestran en mayor medida adquisición excesiva (en particular, por compra).', 'mujeres'),
  ('Mi baraja', '¿Se han hallado más variaciones en el mismo país en zonas urbanas o rurales?', 'Urbanas'),
  ('Mi baraja', 'Trastorno de Adaptación: El DSM 5 establece como factores de riesgo ambiental el haber crecido en entornos de v___ d___ y los factores
e___.', 'vida desfavorecidos, estresantes.'),
  ('Mi baraja', 'Crisis de angustia o ataque de pánico: La sintomatología cognitiva es ___ (más/menos) frecuente en adultos que en niños', 'Más'),
  ('Mi baraja', 'Ansiedad social: En población general, la prevalencia es mayor en mujeres que en hombres ___ (escala numérica). La diferencia de género es superior en ___ y ___. En población clínica, la prevalencia en hombres es ___ o ___ que la de mujeres.', '(2,2:1,5), adolescentes y adultos jóvenes, similar o ligeramente más alta'),
  ('Mi baraja', 'En el modelo tripartito de la ansiedad-depresión, BAJA ACTIVACIÓN SIMPÁTICA pertenece a bajo afecto positivo (anhedonia) / alto afecto negativo (distress) / hiperactivación fisiológica', 'Bajo afecto positivo');
