export const TEMARIO = [
  { curso: "Psicopatología", color: "#2E7D6B", temas: [
    { nombre: "Trastornos del estado de ánimo", contenido: "Episodio depresivo mayor, trastorno bipolar tipo I y II, ciclotimia, distimia. Criterios diagnósticos, curso y diagnóstico diferencial." },
    { nombre: "Trastornos psicóticos", contenido: "Esquizofrenia, trastorno esquizoafectivo, trastorno delirante. Síntomas positivos y negativos, criterios temporales." }
  ]},
  { curso: "Evaluación psicológica", color: "#3B6FA0", temas: [
    { nombre: "Instrumentos de evaluación", contenido: "Tests de personalidad (MMPI, 16PF), tests de inteligencia (WAIS, WISC), entrevistas estructuradas." },
    { nombre: "Fiabilidad y validez", contenido: "Consistencia interna, fiabilidad test-retest, validez de contenido, de constructo y de criterio." }
  ]},
  { curso: "Psicología clínica", color: "#C89B3C", temas: [
    { nombre: "Terapia cognitivo-conductual", contenido: "Modelo ABC, reestructuración cognitiva, técnicas conductuales de exposición y activación." },
    { nombre: "Terapias de tercera generación", contenido: "ACT, terapia dialéctico-conductual, mindfulness aplicado a clínica." },
    { nombre: "Trastornos de la conducta alimentaria", contenido: "Anorexia, bulimia, trastorno por atracón. Criterios diferenciales y abordaje terapéutico." },
    { nombre: "Tema 3: Trastornos bipolares y relacionados", contenido: "Trastorno Bipolar I: requiere al menos 1 episodio maníaco (los episodios depresivos no son necesarios para el diagnóstico, aunque casi siempre aparecen). Trastorno Bipolar II: requiere al menos 1 episodio hipomaníaco Y 1 episodio depresivo mayor, y NUNCA ha existido un episodio maníaco completo (si aparece, pasa a ser Bipolar I). El TB II tiene inicio algo más tardío, mayor cronicidad, más episodios depresivos y mayor riesgo de intentos de suicidio (aunque letalidad similar al TB I) que el TB I. Trastorno Ciclotímico: al menos 2 años (1 en niños/adolescentes) con numerosos períodos de síntomas hipomaníacos y depresivos que NUNCA cumplen criterios completos de episodio; 15-50% evolucionan a TB I o II. Diagnóstico diferencial clave: con esquizofrenia (en TB los síntomas psicóticos son episódicos y con más antecedentes afectivos familiares); con TDAH (en TB debe haber cambio claro respecto a la conducta habitual); con TLP (en TB hay episodios diferenciados, no un patrón reactivo continuo). Especificadores DSM-5: con características mixtas, con ciclos rápidos (≥4 episodios afectivos en 12 meses), con catatonía, con patrón estacional. Epidemiología: el TB es el trastorno mental con mayor influencia genética (heredabilidad hasta 90%; concordancia en monocigóticos 40-70%, PIR 23,157); inicio típico en la veintena. Modelos explicativos: genéticos (poligénico, posible solapamiento con esquizofrenia), bioquímicos (hipótesis noradrenérgica, serotoninérgica permisiva, dopaminérgica; el litio es el fármaco de referencia), psicodinámicos (Freud: manía como defensa frente a la pérdida del objeto amado; Lewin: manía como regresión defensiva frente a la depresión; Klein: la negación como mecanismo de defensa maníaco), y cognitivo de Beck (tríada cognitiva positiva: visión expansiva de uno mismo, el mundo y el futuro, análoga e inversa a la tríada depresiva)." },
    { nombre: "Tema 4: Trastornos de ansiedad", contenido: "Diferencias clave: miedo (reacción ante amenaza presente/real) vs ansiedad (anticipatoria, orientada al futuro) vs angustia (componente físico) vs fobia (miedo desproporcionado + evitación + irracionalidad + malestar). Triple sistema de respuesta de Lang: cognitivo-subjetivo, fisiológico-somático y motor-conductual (pueden disociarse entre sí). Ataque/crisis de pánico: aparición súbita de miedo o malestar intenso que alcanza su pico en minutos con ≥4 de 13 síntomas (palpitaciones, sudoración, temblor, disnea, dolor torácico, náuseas, mareo, desrealización/despersonalización, miedo a perder el control o a morir, parestesias, escalofríos/sofocos); en DSM-5 es un especificador aplicable a cualquier trastorno, no un diagnóstico en sí. Trastorno de Pánico: ataques de pánico inesperados y recurrentes + ≥1 mes de preocupación por nuevos ataques o cambio conductual significativo; comorbilidad frecuente con agorafobia, depresión y consumo de sustancias. Agorafobia: miedo/ansiedad en ≥2 de 5 situaciones (transporte público, espacios abiertos, espacios cerrados, colas/multitudes, estar fuera de casa solo); desde DSM-5 es independiente del Trastorno de Pánico y pueden diagnosticarse ambos a la vez. Fobia específica: miedo intenso ante un objeto/situación concreta; subtipos animal, entorno natural, sangre-inyección-herida (única con respuesta vasovagal de desmayo), situacional y otra; Teoría de la preparación de Seligman: predisposición filogenética a asociar miedo con estímulos ancestralmente peligrosos (selectividad, fácil adquisición, resistencia a la extinción, irracionalidad). Trastorno de Ansiedad Social (antes fobia social): miedo a la evaluación negativa en situaciones sociales o de actuación; modelos de Clark y Wells (procesamiento centrado en uno mismo) y de Rapee y Heimberg (discrepancia entre la impresión que se cree causar y la deseada). TAG: preocupación excesiva e incontrolable durante ≥6 meses sobre múltiples áreas + ≥3 síntomas (inquietud, fatigabilidad, dificultad de concentración, irritabilidad, tensión muscular, alteraciones del sueño); modelo de intolerancia a la incertidumbre (Dugas) y modelo metacognitivo de Wells (preocupaciones tipo I vs tipo II o metapreocupaciones). Modelo de la triple vulnerabilidad de Barlow (biológica generalizada, psicológica generalizada, psicológica específica) y modelo transdiagnóstico jerárquico (neuroticismo/afecto negativo como rasgo de vulnerabilidad común a todos los trastornos emocionales)." },
    { nombre: "Tema 5: TOC y trastornos relacionados", contenido: "TOC (DSM-5): presencia de obsesiones (pensamientos/impulsos/imágenes recurrentes, intrusivos y no deseados que generan ansiedad) y/o compulsiones (comportamientos o actos mentales repetitivos realizados para reducir el malestar o prevenir un suceso temido, sin conexión realista con lo que pretenden neutralizar); ocupan >1 hora al día. Especificador de introspección: con buena/aceptable, con poca, o con ausencia de introspección/creencias delirantes. Contenidos obsesivos más frecuentes: contaminación, daño, simetría/orden, dudas/comprobación, pensamientos tabú. Clasificaciones clásicas: Marks (rituales de limpieza, comprobación, repetición, acumulación, orden; lentitud obsesiva sin rituales visibles; obsesiones puras); las compulsiones de limpieza/lavado son las más frecuentes en clínica, seguidas de comprobación. Modelos explicativos: biológicos (hipótesis serotoninérgica —eficacia de los ISRS—, dopaminérgica, alteraciones en ganglios basales y circuito frontoestriatal); conductual (modelo bifactorial de Mowrer: condicionamiento clásico + mantenimiento por refuerzo negativo mediante la compulsión); cognitivos (Salkovskis: la valoración catastrofista de los pensamientos intrusivos normales —no los pensamientos en sí— los convierte en obsesiones; Rachman: fusión pensamiento-acción, la creencia de que pensar algo malo equivale moralmente a hacerlo). Tratamiento de referencia: exposición con prevención de respuesta (EPR). Trastorno Dismórfico Corporal: preocupación excesiva por defectos físicos mínimos o inexistentes + conductas repetitivas asociadas (mirarse al espejo, compararse, buscar cirugía estética); antes clasificado entre los trastornos somatomorfos. Trastorno de Acumulación: dificultad persistente para desprenderse de posesiones por el malestar que genera hacerlo, independientemente de su valor real; distinguir del Síndrome de Diógenes (abandono extremo del autocuidado e higiene, típico de edad avanzada, no siempre coincide con acumulación). Tricotilomanía: arranque recurrente del propio pelo con intentos fallidos de dejarlo. Trastorno de Excoriación: rascado recurrente de la piel hasta producir lesiones. Trastorno de referencia olfativa: preocupación persistente por creer que se emite un olor corporal desagradable (diagnóstico propio en CIE-11)." }
  ]},
  { curso: "Neuropsicología", color: "#8A5A9E", temas: [
    { nombre: "Funciones cognitivas", contenido: "Atención, memoria, funciones ejecutivas, lenguaje. Síndromes neuropsicológicos principales (afasias, apraxias, agnosias)." }
  ]},
  { curso: "Psicología social", color: "#B0533E", temas: [
    { nombre: "Procesos grupales", contenido: "Pensamiento grupal, polarización, facilitación social, dinámica de roles." },
    { nombre: "Influencia social", contenido: "Conformidad (Asch), obediencia (Milgram), persuasión y cambio de actitudes." }
  ]}
];
